### ISSUE TITLE
Add build and contribution instructions to README

### ISSUE THREAD

**Issue by jvoigtlaender** [elm/package.elm-lang.org#110]
See https://github.com/elm-lang/package.elm-lang.org/issues/51#issuecomment-141880815.

**Comment by jvoigtlaender** [comment]
The README could get some text like in the READMEs of https://github.com/elm-lang/elm-lang.org or https://github.com/elm-lang/elm-compiler.

**Comment by mgold** [comment]
Currently I was able to get this running locally using the instructions [here](https://github.com/elm-lang/elm-lang.org/blob/master/README.md), and then I had to download some files:

```shell
curl -o all-packages.json http://package.elm-lang.org/all-packages
mkdir -p packages/elm-lang/core/3.0.0
cd packages/elm-lang/core/3.0.0/
wget http://package.elm-lang.org/packages/elm-lang/core/3.0.0/README.md
http://package.elm-lang.org/packages/elm-lang/core/3.0.0/documentation.json
```

The individual module pages still 404 for me but this is enough to get started with search issues.

**Comment by jvoigtlaender** [comment]
To get the individual pages displayed (non-404), you will currently have to download also `http://package.elm-lang.org/packages/elm-lang/core/3.0.0/docs/Array.json`, `http://package.elm-lang.org/packages/elm-lang/core/3.0.0/docs/Basics.json`, etc. (and put them into a corresponding subdirectory). These files are anachronistic and shouldn't be needed, but for the moment they are, until [these lines](https://github.com/elm-lang/package.elm-lang.org/blob/9cb327f51084b3e86f4e7028042c4d7e028f2568/src/backend/Routes.hs#L70-L72) are replaced by a test more in line with the new doc/files strategy.

**Comment by mgold** [comment]
Okay thanks for the info! Would you happen to know how how to rebuild the frontend? I'm making changes and compiling with `elm make` but the old files in `artifacts/` are still being served. I imagine there's a script to do this but I can't find it.

**Comment by jvoigtlaender** [comment]
I think I've always been doing `cabal install run-server`, then executed `.cabal-sandbox/bin/run-server`. I've never invoked `elm make` myself. Instead, the `run-server` executable should do that and also put the Elm compilation results in the appropriate place.

**Comment by jvoigtlaender** [comment]
[This function](https://github.com/elm-lang/package.elm-lang.org/blob/3d0be31e10d88ab08fde1e7124cfad9b71ac01f5/src/backend/Main.hs#L90-L105) is the "script" you are looking for. It is called when the `run-server` executable is run (unless [this condition](https://github.com/elm-lang/package.elm-lang.org/blob/3d0be31e10d88ab08fde1e7124cfad9b71ac01f5/src/backend/Main.hs#L49) is false), so you shouldn't have to call `elm-make` yourself at all.

**Comment by mgold** [comment]
I thought about bouncing the server but didn't try it... thanks!

**Comment by Zinggi** [comment]
Since the very recent update you also need
`curl -o new-packages.json http://package.elm-lang.org/new-packages`

Would be good to have a script that gets all the required resource automatically.

**Comment by jvoigtlaender** [comment]
Just in case another set of instructions for the actual building is sought, there's a brief description of "this works" in [that comment](https://github.com/elm-lang/package.elm-lang.org/issues/129#issuecomment-159029222).

**Comment by evancz** [comment]
I think contribution will happen through folks getting involved through community channels. When that person appears with the time and energy, they can make this if they feel it will help them in their work.
