### ISSUE TITLE
Show dependencies on package page

### ISSUE THREAD

**Issue by agrafix** [elm/package.elm-lang.org#147]
It would be very helpful if the main page (eg http://package.elm-lang.org/packages/agrafix/elm-bootforms/4.0.0/ ) of each package would show (and link) its dependencies.

**Comment by jvoigtlaender** [comment]
Agreed. The information is there, though. It is as easy as adding `elm-package.json` to the link. For example, http://package.elm-lang.org/packages/agrafix/elm-bootforms/4.0.0/elm-package.json

**Comment by brasilikum** [comment]
With the current updates to 0.17 going on, it would be especially useful to see the supported elm Version (probably with color coding) right on top of the package.

**Comment by jinjor** [comment]
I agree. Especially, evancz/elm-html is a trap for beginner (I also catch [this](http://package.elm-lang.org/packages/evancz/elm-html/4.0.2) page by googling "elm html").

**Comment by rlefevre** [comment]
For now, you can use the unofficial [elm-package-info](https://github.com/dmy/elm-package-info) browser extension which aims at testing some improvements (including the package dependencies) without requiring changes to the server.

[Firefox extension](https://addons.mozilla.org/en-US/firefox/addon/elm-package-info/) [Chrome extension](https://chrome.google.com/webstore/detail/elm-package-info/egmipcpkalcanmhgjbmkeioigoefjkff)

**Comment by rlefevre** [comment]
Each package now has an "About" page that includes the package dependencies.

**Comment by evancz** [comment]
Thank you to @rlefevre for thinking of putting this info on the `About` page, so it is available without making things to crowded otherwise!
