### ISSUE TITLE
Effect manager review for touch

### ISSUE THREAD

**Issue by doodledood** [elm/package.elm-lang.org#197]
Hello,

I added global touch events to elm-lang/mouse fork. Need those for a project of mine which needs to drag stuff around using touch. Decided it does not belong in Mouse and therefore wanted to publish it as a standalone package.

[Repo is here](https://github.com/doodledood/touch)

**Comment by evancz** [comment]
We are going a different way with effect managers as described [here](https://discourse.elm-lang.org/t/native-code-in-0-19/826). Sorry that our learning process has been messy like this.
