### ISSUE TITLE
Exclude known deprecated packages from search results

### ISSUE THREAD

**Issue by andys8** [elm/package.elm-lang.org#253]
### Issue

Some common libraries from `evancz` were moved to `elm-lang` package. Other's are now `elm-community`. Search engines like Google still refer to deprecated one's. It's hard for beginners to see the difference and a quick search to look up documentation often leads to the wrong result.

### Example

Google `elm html` -> http://package.elm-lang.org/packages/evancz/elm-html/latest/
Google `elm http`-> http://package.elm-lang.org/packages/evancz/elm-http/3.0.1
(and there is no  manual deprecation warning)

https://github.com/evancz?utf8=✓&tab=repositories&q=deprecated
-> `start-app`, `elm-effects`, `virtual-dom`, `elm-svg`

I think there are more results of libraries being transferred to `elm-community`, but it's more complicated because the ownership and state is not perfectly clear.

#### Solution 1: `robots.txt`
Add popular, but deprecated packages to the `robots.txt` file to exclude them from search results.

#### Solution 2: Visualization
Elm Package page list view clearly show's for non updated versions that they're deprecated. The detail view doesn't. This could be done to make it clear for users.

<img width="649" alt="screen shot 2017-10-30 at 16 49 20" src="https://user-images.githubusercontent.com/13085980/32180481-5feda434-bd92-11e7-9c71-1fc961d95ffa.png">
<img width="958" alt="screen shot 2017-10-30 at 16 49 38" src="https://user-images.githubusercontent.com/13085980/32180482-60272fd8-bd92-11e7-911a-9eba94b55732.png">

**Comment by allytamas** [comment]
Same for some packages for which the author removed his Github account: http://package.elm-lang.org/packages/r31gN/elm-dropdown/1.0.2/Dropdown

**Comment by dukedave** [comment]
FYI #285 gets us most of **Solution 2** 🎉 cc @thomasin

**Comment by c-mart** [comment]
This is still a paper cut, and has been made worse with more popular packages moving their namespace for Elm 0.19. Having "latest" in the URL for the old packages (e.g. [here](https://package.elm-lang.org/packages/NoRedInk/elm-decode-pipeline/latest/) and [here](https://package.elm-lang.org/packages/evancz/elm-http/latest/)) is especially misleading.

#285 would help somewhat, but it would be really helpful if old packages are removed from search engine results, with warnings to guide folks toward the newest package. :smiley: 

![image](https://user-images.githubusercontent.com/13605043/57387202-e3528000-7183-11e9-9245-d25eabe81d07.png)

**Comment by andys8** [comment]
![Screenshot_20191116-124018](https://user-images.githubusercontent.com/13085980/68992638-4a0cd080-086e-11ea-87ca-f32580c98ed8.png)


https://github.com/elm/package.elm-lang.org/commit/2a7e80fd909eeb1b90fd5376ad22c0fa6b5f2136

https://github.com/elm/package.elm-lang.org/commit/a356a2d485bc521cfaeeafc84b17aa6997ee416c

**Comment by andys8** [comment]
Great improvements :)

It would be awesome if `evancz` packages could be added to the list. E.g. https://package.elm-lang.org/packages/evancz/elm-html/4.0.0/Html (second result for search "elm html")

**Comment by rlefevre** [comment]
@andys8 See:
https://github.com/elm/package.elm-lang.org/commit/f9c3cc452e7890850ee4e554bda117d8af843cab

**Comment by andys8** [comment]
Nice, so maybe it takes more time. But I think the issue can be closed :) Awesome!
