### ISSUE TITLE
Package view should specify compatible elm versions

### ISSUE THREAD

**Issue by wildeyes** [elm/package.elm-lang.org#255]
Since Elm is an evolving language, not all packages can run on all elm versions.

It'll be helpful if when viewing a package, it'll show which elm versions it's compatible with, so one shouldn't have to use `elm-package install` to find out the package DOESNT actually support her version.

**Comment by rlefevre** [comment]
For now, you can use the unofficial [elm-package-info](https://github.com/dmy/elm-package-info) browser extension which aims at testing some improvements (including the supported elm version) without requiring changes to the server.

[Firefox extension](https://addons.mozilla.org/en-US/firefox/addon/elm-package-info/) [Chrome extension](https://chrome.google.com/webstore/detail/elm-package-info/egmipcpkalcanmhgjbmkeioigoefjkff)

**Comment by rlefevre** [comment]
Each package now has an "About" page that includes the compatible elm version.
Also a warning is displayed for package not compatible with last elm version.
