### ISSUE TITLE
HTML Tags in documentation aren't escaped

### ISSUE THREAD

**Issue by schroffl** [elm/package.elm-lang.org#256]
I just found this [Slider Package](http://package.elm-lang.org/packages/CallumJHays/elm-sliders/1.0.1/Slider) while strolling through the package list, and noticed that it had an actual HTML `input` element in its rendered documentation. I tracked it back to [this comment](https://github.com/CallumJHays/elm-sliders/blob/1.0.1/src/Slider.elm#L13) in the source code.

I'm not sure if this is inteded to be a feature (for whatever reason), because I couldn't find any issue that addresses it and I think it's too strange to not have been noticed before.
But it seemed not quite right to me, so I decided to file an issue myself.

**Comment by evancz** [comment]
This should be resolved in the new version of the site. Thank you for the report!
