### ISSUE TITLE
Show package license on its page

### ISSUE THREAD

**Issue by easimonenko** [elm/package.elm-lang.org#258]
We can find out the license for a package if we look in the repository, but it would be nice to see the license right on the package page.

**Comment by rlefevre** [comment]
For now, you can use the unofficial [elm-package-info](https://github.com/dmy/elm-package-info) browser extension which aims at testing some improvements (including the package license) without requiring changes to the server.

[Firefox extension](https://addons.mozilla.org/en-US/firefox/addon/elm-package-info/) [Chrome extension](https://chrome.google.com/webstore/detail/elm-package-info/egmipcpkalcanmhgjbmkeioigoefjkff)

**Comment by rlefevre** [comment]
Each package now has an "About" page that includes the license.

**Comment by evancz** [comment]
Thanks to @rlefevre for figuring out a nice design for this!

https://package.elm-lang.org/packages/elm/core/latest/about
