### ISSUE TITLE
Effect manager review for https://github.com/relabsoss/elm-gmap

### ISSUE THREAD

**Issue by tvv** [elm/package.elm-lang.org#262]
Google map effect manager

[Repo link](https://github.com/relabsoss/elm-gmap)

**Comment by rtfeldman** [comment]
Hi @tvv, I think there may be some confusion. Have you read [this post](https://discourse.elm-lang.org/t/native-code-in-0-19/826) by any chance?

**Comment by evancz** [comment]
We are going in a different direction as described in the post linked by @rtfeldman. Sorry for the trouble.
