### ISSUE TITLE
Unpublish `spaxe/svg-pathd` in favour of `Spaxe/svg-pathd`

### ISSUE THREAD

**Issue by Spaxe** [elm/package.elm-lang.org#263]
I bumped into an issue where the capitalisation of the username on Github needs to match, or elm-package will fail to download the package (https://github.com/elm-lang/elm-package/issues/273).

**Comment by Spaxe** [comment]
Looks like the package.elm-package.org also doesn't link to the uppercase one: http://package.elm-lang.org/packages/Spaxe/svg-pathd/latest

**Comment by evancz** [comment]
Done!
