### ISSUE TITLE
How to compile/serve

### ISSUE THREAD

**Issue by FranzSkuffka** [elm/package.elm-lang.org#265]
I would like to contribute but I don't know how to work on this site. I currently use stack as my environment. Is there a simple way to launch a web server that updates when I modify the source?

Can we add this to the README.md?

**Comment by evancz** [comment]
The http://elm-lang.org/community#participate section has some good links on what to prioritize in an effort to do open source work.

It is really hard to build, so there are not clear instructions at this time. I understand that if there were instructions, perhaps a chaotic disorganized sort of collaboration is possible, but that's generally not the sort of collaboration that we do in the Elm community, especially for important infrastructure projects.
