### ISSUE TITLE
Effect manager review for device-orientation package

### ISSUE THREAD

**Issue by igor-drozdov** [elm/package.elm-lang.org#267]
Hi

I've created a package for receiving [Device Orientation API](https://www.w3.org/TR/orientation-event/) data via Elm: https://github.com/igor-drozdov/elm-device-orientation
It also contains subscription for Device Motion. I decided to put them in one package, cause they are usually associated with each other.

Apparently, I can't publish it without review, since it's an `effect module`. But it seems to be an appropriate use case for an `effect module` just like [elm-lang/geolocation](https://github.com/elm-lang/geolocation) and [elm-lang/page-visibility](https://github.com/elm-lang/page-visibility).

What do you think?

**Comment by BrianHicks** [comment]
let's keep discussion on this to the elm-dev thread you opened. 😄
