### ISSUE TITLE
Middle mouse button clicks open in same tab rather than a new tab

### ISSUE THREAD

**Issue by neurodynamic** [elm/package.elm-lang.org#268]
A middle-mouse-button click navigates to the link within the same tab. Expected behavior would be to open the clicked link in a new tab.

**Comment by evancz** [comment]
Can you do a hard refresh of the website and see if you get the fixed behavior? If it is still broken, please tell me what browser and OS you are using.

**Comment by neurodynamic** [comment]
All fixed. Works great!

**Comment by evancz** [comment]
Cool, thanks for the report!
