### ISSUE TITLE
I'm lazy and a newb, can I have a copy-and-paste instruction to install a package?

### ISSUE THREAD

**Issue by evaryont** [elm/package.elm-lang.org#27]
A line along the following:

> To install this package, execute the following in your project directory:
> `elm-make install elm-lang/core`

Of course, language and terms should be clarified but it gets the point across. Thoughts?

**Comment by Apanatshka** [comment]
I think it's `elm package install elm-lang/core` as of 0.15. Where would you expect this information to be? That is, where is it missing?

**Comment by evaryont** [comment]
Ah, sorry, should've been more descriptive. It would be useful on each package's page. For instance, on [`elm-lang/core`](http://package.elm-lang.org/packages/elm-lang/core/2.0.1)'s page, there would be a code block for easy copy & paste to a user's shell to install the package, like [Rubygems has](https://rubygems.org/gems/rails) (see the sidebar).

It had taken me a bit to realize what the exact command I was supposed to use to install packages is.

**Comment by Apanatshka** [comment]
That's a good idea. Like most version control hosting websites have a clone box. Sounds like a simple addition to the page. Maybe something you can try to add yourself and submit as a PR? It's a nice small thing to start contributing with :)

**Comment by Zinggi** [comment]
So I started implementing this, as I also found it lacking.
It currently looks like this:
![screenshot from 2015-11-23 11-58-00](https://cloud.githubusercontent.com/assets/3420308/11336304/63171d74-91e4-11e5-920f-81d0e1b62856.png)

There is a small hack there because I don't think this is currently possible in elm-html.
I used:

    attribute "onClick" "this.select()"

Is this hack acceptable?
Would be cool if I could do this in elm-html with something like

    selected model.selected

instead.

If you're ok with the design and if this hack is acceptable, I'm gonna send a pull request.
Let me know.

**Comment by megapctr** [comment]
Is anyone working on this? I could try to prepare a PR.

IMO there doesn't even have to be a copy-to-clipboard button, all I would care about is having the full package name in a valid format (author + name, without spaces around the slash, etc)

**Comment by pete-a** [comment]
IMO, NPM's solution is simple and effective:
![npm install helper](https://cloud.githubusercontent.com/assets/13892/23099103/0e9b5cda-f6b3-11e6-8ad8-8ab5e22c278a.png)

E.g just like @Zinggi 's solution though no need for auto copy functionality, plus a simple link to show beginners how to use `elm package`

**Comment by drathier** [comment]
@megapctr it doesn't seem like anyone is working on this, no. And the header is very hard to copy, since trying to select the words just grabs the link instead, and it's very easy to select the version.

**Comment by megapctr** [comment]
@drathier there's a MR fixing the header, but for some reason it seems it's being ignored? https://github.com/elm-lang/package.elm-lang.org/pull/209

**Comment by drathier** [comment]
@megapctr ah. I would still like a copy/pastable command in a textbox, like git clone here on github. It's not _that_ simple to figure out you can copy/paste the text in the header, and it does take a few extra seconds each time.

**Comment by mandrolic** [comment]
Ate the risk of adding a 'Me Too' reply here - I just noticed this - it seems conspicuous by it's absence. NPM, Nuget, Docker, etc all have this snippet, it's kinda _expected_ now. There is a little bit of a risk that a user will currently reach an Elm package page and end up thinking "That's nice.... now what?"

**Comment by Razzeee** [comment]
Just looked over a colleagues shoulder last friday, he just recently started to explore elm. And exactly this was what he was looking for, so I had to say, you can copy the header.

He then pasted into iTerm2 and it got seperated over three lines :/

**Comment by rlefevre** [comment]
For now, you can use the unofficial [elm-package-info](https://github.com/dmy/elm-package-info) browser extension which aims at testing some improvements (including the package installation instructions with copy-to-clipboard on click) without requiring changes to the server.

[Firefox extension](https://addons.mozilla.org/en-US/firefox/addon/elm-package-info/) [Chrome extension](https://chrome.google.com/webstore/detail/elm-package-info/egmipcpkalcanmhgjbmkeioigoefjkff)

**Comment by rlefevre** [comment]
Each package now has an "About" page that includes the install command for last elm version.

**Comment by evancz** [comment]
Thank you to @rlefevre for thinking of having an `About` page to show this information in a nice way!
