### ISSUE TITLE
Internal UploadedFiles server error when attempting to publish a new package

### ISSUE THREAD

**Issue by ianmackenzie** [elm/package.elm-lang.org#270]
When attempting to publish `ianmackenzie/elm-geometry` 1.0.0, I get the following error:

```
c:\Git\ianmackenzie\elm-geometry-0.18>elm package publish
Verifying ianmackenzie/elm-geometry 1.0.0 ...
This package has never been published before. Here's how things work:

  * Versions all have exactly three parts: MAJOR.MINOR.PATCH

  * All packages start with initial version 1.0.0

  * Versions are incremented based on how the API changes:

        PATCH - the API is the same, no risk of breaking code
        MINOR - values have been added, existing values are unchanged
        MAJOR - existing values have been changed or removed

  * I will bump versions for you, automatically enforcing these rules

The version number in elm-package.json is correct so you are all set!
Error: The following HTTP request failed.
<http://package.elm-lang.org/register?elm-package-version=0.18&name=ianmackenzie%2Felm-geometry&version=1.0.0>

A web handler threw an exception. Details:
File upload exception: Internal error! UploadedFiles: opened new file with pre-existing open handle
```

I worry that I may have broken something by messing up the package publishing workflow slightly...here's the sequence of events:

  - I renamed `opensolid/geometry` to `ianmackenzie/elm-geometry` (and forked back to `opensolid/geometry`).
  - After making a bunch of code changes to `elm-geometry`, I went to run `elm package publish`. I noticed that the output was still referring to `opensolid/geometry`, so I aborted the command with Ctrl-C.
  - I realized that I had forgotten to update `elm-package.json`, so I fixed it to have the correct repository URL (github.com/ianmackenzie/elm-geometry instead of github.com/opensolid/geometry) and version (1.0.0 instead of 2.1.0).
  - Trying to run `elm package publish` again then led to the above error output.
  - I tried running `elm package publish` on a separate computer with a separate IP address, to see if it was related to a local cache or a specific user session on the server, but same error.

I'm on Windows 10 using Elm 0.18.

**Comment by evancz** [comment]
Yeah, there was a partial publish on there. I got rid of it. Try again and close if it's resolved!

**Comment by ianmackenzie** [comment]
Thanks so much for the quick response! I just tried again and got the same error, though. Is there anything else I should be doing (cleaning out `elm-stuff` and `~/.elm` etc.)?

**Comment by evancz** [comment]
Yes to both. Let's switch to DM on Slack for the rest though.

**Comment by surprisetalk** [comment]
Sorry to post on a closed issue, but I just encountered the same problem:
```
Verifying surprisetalk/elm-icon 3.0.0 ...
Version number 3.0.0 verified (MAJOR change, 2.0.1 => 3.0.0)
Error: The following HTTP request failed.
<http://package.elm-lang.org/register?elm-package-version=0.18&name=surprisetalk%2Felm-icon&version=3.0.0>

A web handler threw an exception. Details:
File upload exception: Internal error! UploadedFiles: opened new file with pre-existing open handle
```

I don't have any naming or version problems like @ianmackenzie , but my package is quite large. Maybe it's hitting the 512KB upload-limit and returning a different error?

Let me know if there's anything I can do to help!

**Comment by evancz** [comment]
Yes, we found that it was related to the upload limit. Try finding @ianmackenzie on Slack if you want to hear what he ended up doing.

In future, it's fine to open a new issue. It becomes quite hard for anyone (myself and others) to understand what's going on once it gets past three or four focused comments.
