### ISSUE TITLE
Problem publishing package update

### ISSUE THREAD

**Issue by jwoLondon** [elm/package.elm-lang.org#271]
This probably relates to #270, but I have just tried to publish an update to [elm-vega](http://package.elm-lang.org/packages/gicentre/elm-vega/latest) (major version bump to 3.0.0). The new additions are large (16,000 lines of code) so perhaps some maximum file size cap?

The error reported:

```
Verifying gicentre/elm-vega 3.0.0 ...
Version number 3.0.0 verified (MAJOR change, 2.3.1 => 3.0.0)
Error: The following HTTP request failed.
<http://package.elm-lang.org/register?elm-package-version=0.18&name=gicentre%2Felm-vega&version=3.0.0>

A web handler threw an exception. Details:
File upload exception: Internal error! UploadedFiles: opened new file with pre-existing open handle
```

I am not a frequent slack user, so cannot find any details of how this might have been solved in the past.

**Comment by jwoLondon** [comment]
With help from @ianmackenzie on Slack it looks like the problem is that the auto-generated documentation.json  weighs 682kb and that published packages cannot have any files >512kb.

The reason the file is this large is that the modules contain many functions that are comprehensively documented (in an attempt to follow good practice and ease the use of the API).

@evancz is there any chance of raising the file size limit for publication?

**Comment by evancz** [comment]
The discussion ended up taking place on https://discourse.elm-lang.org/t/publishing-a-package-with-api-documentation-512kb/1562
