### ISSUE TITLE
Visualize deprecation of "elm-lang" packages

### ISSUE THREAD

**Issue by andys8** [elm/package.elm-lang.org#275]
"elm-lang/" is now "elm/". Old documentation is available. A hint should highlight there is a newer version available or that the version shown is deprecated.

### Example

`elm-lang/core`: 
https://package.elm-lang.org/packages/elm-lang/core/4.0.5/Platform-Cmd

shows 
> Warning! The latest version of this package is 5.1.1

and links to

https://package.elm-lang.org/packages/elm-lang/core/latest/Platform-Cmd

which is deprecated, but there is *no indication*. 

Current package: https://package.elm-lang.org/packages/elm/core/latest/Platform-Cmd

### Relevance

The example link to `elm-lang/core` is referenced in the top Google search result for "elm bang": An answer at stackoverflow: https://stackoverflow.com/a/38525436

`(!)` was removed. The (previous) documentation contains the operator and has no indication it's not the latest version (which is addressed with this issue).

**Comment by jinjor** [comment]
Agreed. I think the simplest way is to show that they are **for 0.18**, because some popular packages have changed their names too.

- elm-lang / * => elm / *
- elm-community / elm-test => elm-explorations / test
- NoRedInk / elm-decode-pipeline => NoRedInk / elm-json-decode-pipeline
- mdgriffith / style-elements => mdgriffith / elm-ui

**Comment by rlefevre** [comment]
For now, you can use the unofficial [elm-package-info](https://github.com/dmy/elm-package-info) browser extension which aims at testing some improvements (including supported elm version) without requiring changes to the server.

[Firefox extension](https://addons.mozilla.org/en-US/firefox/addon/elm-package-info/) [Chrome extension](https://chrome.google.com/webstore/detail/elm-package-info/egmipcpkalcanmhgjbmkeioigoefjkff)

**Comment by rlefevre** [comment]
Each package now has an "About" page that includes the compatible elm version.
Also warnings have been added for package not compatible with last elm version, or for `elm-lang/` packages moved to `elm/`.

**Comment by evancz** [comment]
We did a couple things to make the `elm-lang` packages show up less in search results, like using `robots.txt` to ask crawlers to not even index them anymore. But with the recent update, we also put a label in case anyone ends up there nonetheless!

![Screen Shot 2020-02-19 at 10 19 38 PM](https://user-images.githubusercontent.com/1658058/74897763-160de380-5366-11ea-9b62-168f0dd55070.png)
