### ISSUE TITLE
Not responding to requests from Russia?

### ISSUE THREAD

**Issue by norpadon** [elm/package.elm-lang.org#278]
I'm continually getting connection timeouts when trying to access package.elm-lang.org from my home network (188.123.252.148) or my company's VPN (2a02:6b8:0:3710::1:6) using elm init, safari, chrome or curl from different devices. But site opens when I use swiss VPN.

**Comment by jenfan** [comment]
no way to install any package or just make elm init =( same country, same problem

**Comment by jenfan** [comment]
@norpadon I found a decision: make a hotspot from mobile and SET VPN ON MOBILE, not on the mac. and you can do elm init :)

**Comment by AleXoundOS** [comment]
Same for me (using onlime.ru provider).

Interesting that it responds to ping:
```console
$ ping -c4 package.elm-lang.org
PING package.elm-lang.org (159.89.227.162) 56(84) bytes of data.
64 bytes from package.elm-lang.org (159.89.227.162): icmp_seq=1 ttl=48 time=125 ms
64 bytes from package.elm-lang.org (159.89.227.162): icmp_seq=2 ttl=48 time=126 ms
64 bytes from package.elm-lang.org (159.89.227.162): icmp_seq=3 ttl=48 time=126 ms
64 bytes from package.elm-lang.org (159.89.227.162): icmp_seq=4 ttl=48 time=126 ms
```

However no success with wget, it hangs for several minutes and finally times out:
```console
$ wget package.elm-lang.org
--2018-10-27 02:35:41--  http://package.elm-lang.org/
Resolving package.elm-lang.org (package.elm-lang.org)... 159.89.227.162
Connecting to package.elm-lang.org (package.elm-lang.org)|159.89.227.162|:80... failed: Connection timed out.
Retrying.
```

Same for curl:
```console
$ curl package.elm-lang.org
curl: (7) Failed to connect to package.elm-lang.org port 80: Connection timed out
```

Using Tor helps, curl with proxy over Tor:
```console
$ curl --socks5-hostname 127.0.0.1:9050 package.elm-lang.org
<html>
<head><title>301 Moved Permanently</title></head>
<body bgcolor="white">
<center><h1>301 Moved Permanently</h1></center>
<hr><center>nginx/1.10.3 (Ubuntu)</center>
</body>
</html>
```

As I understand the `elm` binary supports only HTTP proxy and not SOCKS. So what's the right way of configuring environment for development in elm in this case?

**Comment by AleXoundOS** [comment]
Same https://github.com/elm/core/issues/994.

**Comment by AleXoundOS** [comment]
Managed to get it to work with [polipo](https://www.irif.fr/~jch/software/polipo/) as an [additional HTTP Proxy over Tor](https://wiki.archlinux.org/index.php/Tor#HTTP_proxy). Proxy environment variable set as `export https_proxy=127.0.0.1:8118`. So that elm is able to pick the `https_proxy` setting.

**Comment by AleXoundOS** [comment]
Figured out why `torsocks` does not work. According to [man page](https://manpages.debian.org/testing/torsocks/torsocks.8.en.html) `torsocks`:
> overloads the libc symbols use for Internet communication

The technique it uses is dynamic library injection using `LD_PRELOAD`. Since the elm-platform binary I use is fully statically linked (has no dependencies on .so files):
```console
$ ldd /bin/elm
        not a dynamic executable
```

... overloading does nothing for it.

**Comment by tdorzhi** [comment]
Having same problem, but the response is rather different: Connection Refused, though IP is pingable.
Anyone can point me if I can use 

> Proxy environment variable set as `export https_proxy=127.0.0.1:8118`. So that elm is able to pick the `https_proxy` setting.

but with SOCKS5 instead?

**Comment by rlefevre** [comment]
The `elm` binary does not support SOCKS proxies using the `https_proxy` environment variable, only HTTPS ones.

Using an HTTP proxy between `elm` and a SOCKS proxy (as provided by Tor for example) could help. [This link](https://www.marcus-povey.co.uk/2016/03/24/using-tor-as-a-http-proxy/) provides a description using polipo as said early in the thread.

Also see https://github.com/elm/compiler/issues/1840 for some information about `elm` and the `https_proxy` environment variable.

**Comment by tdorzhi** [comment]
Thanks. So sad Russia banned the site for no particular reason...

**Comment by and-semakin** [comment]
Banned because it's hosted on DigitalOcean. So we have to use proxy now.

![image](https://user-images.githubusercontent.com/9129071/52547308-9fe8af80-2de8-11e9-9a47-cbd187e585b5.png)
(Screenshot from @rkn_block_check_bot Telegram bot).

**Comment by AleXoundOS** [comment]
It would be nice to have instructions on how to create a mirror.

**Comment by AleXoundOS** [comment]
Not a mirror, but one kind of a local solution: https://github.com/drathier/elm-offline. Based on elm-compiler code and a small python script. Currently not a polished project, taking full contents of the former elm-compiler repository. But we have to appreciate the author for the work on this.

**Comment by rlefevre** [comment]
Until an official solution is found, you could use the package.elm-lang.org proxies described in [this gist](https://gist.github.com/rlefevre/7c21513c3cc14ea23524223ab35e4ca6#file-elm-dmy-fr-md). It should be easier to use than a VPN, particularly for CI.

**Comment by AlexAkulov** [comment]
Зачем вам elm когда есть водка?

**Comment by AleXoundOS** [comment]
> Зачем вам elm когда есть водка?

Candidate for abuse report.

**Comment by kaimu** [comment]
An IPv6 address could be a nice temporary solution.

**Comment by rlefevre** [comment]
I have also added a reverse proxy to browse documentation for packages < 0.19:
https://old.elm.dmy.fr/

To use 0.18 `elm-make` and `elm-package`, use:
```
$ http_proxy=elm.dmy.fr:9999 elm-make [...]
$ http_proxy=elm.dmy.fr:9999 elm-package ...
```
I have updated the [gist](https://gist.github.com/rlefevre/7c21513c3cc14ea23524223ab35e4ca6) with instructions.

**Comment by zergera** [comment]
@rlefevre Thanks! It's brilliant!

**Comment by norpadon** [comment]
Валите из этой страны пока не поздно, ребята

**Comment by evancz** [comment]
The site has a new IP address. Is it working for people in Russia now?

**Comment by randomer** [comment]
Looks like it does! Thank you so much! 🙏

**Comment by kaimu** [comment]
It works. Thanks a lot!

**Comment by evancz** [comment]
Great, glad we figured out some sort of fix!
