### ISSUE TITLE
Improvement: add the "elm install XX/YYYY" , depreciated, does it work with 0.18, 0.19....?

### ISSUE THREAD

**Issue by mattiasw2** [elm/package.elm-lang.org#288]
I always have to guess the name used by "elm install" Maybe it is as simple taking the first 2 parts after /packages/ in the url, but I seem to remember cases where this is not true.

For example, https://package.elm-lang.org/packages/elm/url/1.0.0/Url

-----

There is no mentioning that https://package.elm-lang.org/packages/NoRedInk/elm-decode-pipeline/3.0.1/ is replaced by https://package.elm-lang.org/packages/NoRedInk/elm-json-decode-pipeline/1.0.0/ on the package site, but it says something about this on the github page.

----

How do I know if this package works with 0.19 by just looking at the package site?

**Comment by stevensonmt** [comment]
Agreed that the package site should indicate if packages are not suitable for elm 0.19. For instance `elm-lang/dom` was deprecated for `Browser.Dom` but the package site does not indicate this and using `elm install elm-lang/dom` returns a cryptic error message about an old version of `List.Extra`.

**Comment by dukedave** [comment]
See also #275

**Comment by rlefevre** [comment]
For now, you can use the [elm-package-info](https://github.com/dmy/elm-package-info) browser extension which aims at testing some improvements (including supported elm version and packages installation instructions) without requiring changes to the server.

[Firefox extension](https://addons.mozilla.org/en-US/firefox/addon/elm-package-info/) [Chrome extension](https://chrome.google.com/webstore/detail/elm-package-info/egmipcpkalcanmhgjbmkeioigoefjkff)

**Comment by rlefevre** [comment]
Each package now has an "About" page that includes an install command and compatible elm version.

**Comment by evancz** [comment]
Most of your suggestions are addressed by the latest update of the website, but there is not a mechanism for marking packages as "deprecated" right now. Perhaps we can track that specific suggestion in a separate issue.
