### ISSUE TITLE
Basics.toString listed even though not exposed anymore in 0.19

### ISSUE THREAD

**Issue by cstork** [elm/package.elm-lang.org#297]
See https://package.elm-lang.org/packages/elm-lang/core/latest/Basics#toString

**Comment by Razzeee** [comment]
Your looking at the old elm 0.18 package, I know it's confusing. All previous `elm-lang` packages are under `elm` now. 

So you're looking for:
https://package.elm-lang.org/packages/elm/core/latest/Basics

**Comment by cstork** [comment]
Hmm, indeed. Thank you!

Maybe put a note on those `elm-lang` pages that they only apply up to version 0.18 ?

**Comment by evancz** [comment]
Yes, I'd like to add a note about that!
