### ISSUE TITLE
Make page load faster by using Production Build

### ISSUE THREAD

**Issue by bbkane** [elm/package.elm-lang.org#301]
https://package.elm-lang.org/ scores a [73 on Google Page Insights](https://developers.google.com/speed/pagespeed/insights/?url=https%3A%2F%2Fpackage.elm-lang.org%2F).

Elm is advertised as being one of the fastest reactive frameworks, so this surprised me. 

Looking at the [source](view-source:https://package.elm-lang.org/), I think a large part of this is because the build artifacts aren't optimized or minified. I bet it could be improved by using similar instructions to [elm-spa-example](https://github.com/rtfeldman/elm-spa-example#production-build).

**Comment by SidneyNemzer** [comment]
Just wanted to point out that you're probably looking at the score for **mobile** which mostly tests the same stuff as desktop, but significantly throttles network speed. If you switch to "Desktop", you'll see a much higher score.

![image](https://user-images.githubusercontent.com/21203108/57119582-36f64100-6d20-11e9-90ea-e7f7b6277adc.png)
![image](https://user-images.githubusercontent.com/21203108/57119584-39f13180-6d20-11e9-8281-0644401fc038.png)

**Comment by bbkane** [comment]
Good to know, but I browse docs on my phone too.

**Comment by evancz** [comment]
I think https://elm.dmy.fr is a good way to browse on mobile for now. @rlefevre has done a great job adding nice features to his parallel version.

The current build script [here](https://github.com/elm/package.elm-lang.org/blob/master/build.sh#L26) does minification, so the downloaded JS is just 32.51 KB on my browser (with gzip)
