### ISSUE TITLE
Broken link to packages

### ISSUE THREAD

**Issue by rgtk** [elm/package.elm-lang.org#302]
[This page](https://package.elm-lang.org/packages/elm/browser/latest/Browser#documents) links to `rtfeldman/elm-css` package targeted at https://package.elm-lang.org/rtfeldman/elm-css/latest/ which renders 404 because URL path is missing `packages/` in path (proper link should be https://package.elm-lang.org/packages/rtfeldman/elm-css/latest/)

I don't know if link always pointed to wrong URL or routing changed for package backend. If the latter is true, maybe backend could fallback to existing package for URL without `packages/` to avoid breaking links and don't maintain the culture of breaking references across WWW pages.

**Comment by andys8** [comment]
Are you referring to this link? It seems to be working/fixed.
![Screenshot_20191116-130551](https://user-images.githubusercontent.com/13085980/68992904-eb495600-0871-11ea-84be-d38acfd16365.png)

**Comment by rlefevre** [comment]
This has been fixed in `elm/browser` by https://github.com/elm/browser/commit/b4548b8cdc3215b7bdd6a07f3fdc96c2264898db released in version 1.0.2.

This issue can be closed.
