### ISSUE TITLE
Example of setViewportOf from Browser-Dom doesn't compile

### ISSUE THREAD

**Issue by MargaretKrutikova** [elm/package.elm-lang.org#306]
I am trying the examples from `Browser-Dom`, and the one with [`setViewportOf`](https://package.elm-lang.org/packages/elm/browser/latest/Browser-Dom#setViewportOf) doesn't seem to compile:
```
jumpToBottom : String -> Cmd Msg
jumpToBottom id =
  Dom.getViewportOf id
    |> Task.andThen (\info -> Dom.setViewportOf id 0 info.scene.height)
    |> Task.perform (\_ -> NoOp)
```

gives error on `Task.perform (\_ -> NoOp)` saying that the argument is `Task.Task Dom.Error ()` when `Task.Task Never ()` is expected by `Task.perform`.

I think it should be `Task.attempt` instead of `Task.perform` since `getViewportOf` returns `Task Error Viewport`.

Or am I missing something? 🙂

**Comment by rlefevre** [comment]
This has been fixed in `elm/browser` by https://github.com/elm/browser/pull/65.
The fixed example is:
```
jumpToBottom : String -> Cmd Msg
jumpToBottom id =
    Dom.getViewportOf id
        |> Task.andThen (\info -> Dom.setViewportOf id 0 info.scene.height)
        |> Task.attempt (\_ -> NoOp)
```
This issue can be closed.
