### ISSUE TITLE
Search doesn't find package if any version requires Elm 0.19.1 as minimum

### ISSUE THREAD

**Issue by malaire** [elm/package.elm-lang.org#315]
For example package [justgook/elm-image](https://package.elm-lang.org/packages/justgook/elm-image/latest/) has two versions: 1.0.0 requires Elm `0.19.0 <= v < 0.20.0` and 2.0.0 requires Elm `0.19.1 <= v < 0.20.0`.

Because there is a version (2.0.0) which requires Elm 0.19.1 as minimum, this package can't be found with search at https://package.elm-lang.org/

Note that this package does have a version (1.0.0) compatible with Elm 0.19.0, so all versions are not incompatible with 0.19.0. So even if search is meant to show only packages compatible with Elm 0.19.0, this package should still be included.

**Comment by evancz** [comment]
I looked through the code that might lead to behavior like this, but I'm not seeing anything that would detect something like this.

Are you sure this wasn't an issue with browser caching? Could you replicate this in another browser? I noticed they did a 2.0.1 that changes this, so maybe we can find another package in the repo that has a `0.19.1 <= v < 0.20.0` constraint that _does_ show up?

(As an aside, it is better to release with the widest range possible, so `0.19.0 <= v < 0.20.0` is definitely better.)

**Comment by evancz** [comment]
Ahh, I think I found it!

https://github.com/elm/package.elm-lang.org/blob/master/src/backend/Memory.hs#L83

The server itself is on 0.19.0 so this check would cause the behavior you describe.

I'll see if I can get it fixed in the least risky way!

**Comment by rlefevre** [comment]
> so maybe we can find another package in the repo that has a 0.19.1 <= v < 0.20.0 constraint that does show up
At the moment, there is no other package in this situation (to check the fix).

**Comment by malaire** [comment]
> (As an aside, it is better to release with the widest range possible, so 0.19.0 <= v < 0.20.0 is definitely better.)

If package is affected by one of the bugs present in 0.19.0 but fixed in 0.19.1, then using 0.19.0 <= v < 0.20.0 would be incorrect.

**Comment by evancz** [comment]
This should be fixed by https://github.com/elm/package.elm-lang.org/commit/c2d675c341f80a46f18ee3770f6cc62db248724d which is live on the site now. Thank you for the report!

**Comment by rlefevre** [comment]
This does not seem to work, see for example the following packages only available on `0.19.1` and above:
* [`showell/meta-elm`](https://package.elm-lang.org/packages/showell/meta-elm/5.1.0)
* [`showell/binary-tree-diagram`](https://package.elm-lang.org/packages/showell/binary-tree-diagram/1.0.1)
* [`showell/dict-dot-dot`](https://package.elm-lang.org/packages/showell/dict-dot-dot/1.0.1)

None of them is listed when searching for example `showell`.

**Comment by evancz** [comment]
@rlefevre, can you open a new issue for this?

**Comment by evancz** [comment]
I made the change suggested, and restarted the server. All the packages you mention are showing up in search now. If there are further problems, please open a new issue!
