### ISSUE TITLE
Broken semver image in README.md

### ISSUE THREAD

**Issue by nelsonic** [elm/package.elm-lang.org#318]
Hi! 👋 
Thanks for all the amazing work you do!

# Problem

While reading the Elm Guide structure section: https://guide.elm-lang.org/webapps/structure.html
There is a link to _this_ repo:
![elm-guide-link-to-elm-package](https://user-images.githubusercontent.com/194400/70320927-d7b06000-181d-11ea-88e8-7675d512a7d2.png)

When reading the `README.md` file we see a broken image:
![elm-package-semver-image-broken](https://user-images.githubusercontent.com/194400/70320785-80aa8b00-181d-11ea-97a5-6aacbacfc915.png)

Initially we thought it was just because the https://github.com/elm-lang/elm-lang.org had moved to https://github.com/elm/elm-lang.org but when we attempted to search for the file in that repo
https://github.com/elm/elm-lang.org/search?q=semver.png&unscoped_q=semver.png
![image](https://user-images.githubusercontent.com/194400/70321347-fd8a3480-181e-11ea-8a09-43c96ef264a6.png)

No results were returned.

Enforced Semantic Versioning is mentioned on https://elm-lang.org/ landing page:
![image](https://user-images.githubusercontent.com/194400/70322864-2d3b3b80-1823-11ea-85aa-edb4278fb919.png)
But it's not an _image_ that could be included in this repo. 

# Proposed Fix

Can we update the image with an alternative? [google.com/search?q=semver.png&tbm=isch](https://www.google.com/search?q=semver.png&tbm=isch)

E.g:
![image](https://user-images.githubusercontent.com/194400/70321527-7093ab00-181f-11ea-9ff3-bf8c3e651f5d.png)
Credit: https://www.geeksforgeeks.org/introduction-semantic-versioning

![image](https://user-images.githubusercontent.com/194400/70321027-20681900-181e-11ea-87df-b9f836e8c7ed.png)
Credit: https://medium.com/@wakingrufus/semantic-versioning-96cff0830736

![image](https://user-images.githubusercontent.com/194400/70321128-73da6700-181e-11ea-92e8-3b604c76b5c0.png)
Credit: https://blog.greenkeeper.io/introduction-to-semver-d272990c44f2

Alternatively, we could _create_ a new image in a few minutes with the same information 
but with the font and color matching https://elm-lang.org so that the image looks "on brand". 
![image](https://user-images.githubusercontent.com/194400/70321781-31198e80-1820-11ea-8eb9-8f047fd92139.png)

Hero image font: https://fonts.google.com/specimen/IBM+Plex+Sans
Background color: `#1293D8`

e.g:
![image](https://user-images.githubusercontent.com/194400/70328263-7fcf2480-1830-11ea-9dbf-889cedc817c5.png)
All yours. No Rights Reserved.

Automatic enforced semantic versioning is a _major_ benefit of the Elm ecosystem. 🎉 
it's worth having an image to explain it. (_or at least **not** having a "**broken**" **image**_) 💔

**Comment by rlefevre** [comment]
The image can be found in git history and is actually this one:
https://github.com/elm/elm-lang.org/blob/d1805d6278fe6a7b8c7e34d034b9180eb97c7bed/static/assets/home/semver.png

It has been removed by this commit:
commit 2116e35ae445bb78609dd6f86abb068b7ce28612
Author: Evan Czaplicki <evancz@users.noreply.github.com>
Date:   Mon Aug 20 22:58:46 2018 -0400

    Get rid of pictures that are not used anymore

**Comment by evancz** [comment]
I think it would be best to find an example that is small and valid with 0.19. If you know of a particular package that could be a good fit, please message me about it!

**Comment by evancz** [comment]
Going to try to use this one:

![webgl-diff](https://user-images.githubusercontent.com/1658058/106834334-3a3ffe80-6663-11eb-9d45-dafd6982506a.png)

It is not as perfect of a showcase, but I think it's a decent fix. Thank you to @nelsonic for the semver explanation art too! I think it would be cool to have something like that to help explain, but I'm not sure how to do the additional edits to make it flow nicely with the existing text.

**Comment by evancz** [comment]
Oh, or just the one from the main website!

![json-diff](https://user-images.githubusercontent.com/1658058/106834628-cd793400-6663-11eb-8cfc-b6d3a5a16c05.png)
