### ISSUE TITLE
Use gzip to compress docs.json?

### ISSUE THREAD

**Issue by ianmackenzie** [elm/package.elm-lang.org#320]
Just noticed that using gzip to compress `docs.json` files was mentioned in https://discourse.elm-lang.org/t/publishing-a-package-with-api-documentation-512kb/1562/11 but there wasn't a tracking issue I could see, so I thought I'd take the liberty of opening one.

I'm running up agains the `docs.json` size limit for `elm-geometry` again - I've already gone through a few iterations of trimming down existing docs, and I'm being pretty terse with documentation for newly-added functions, but I'm still up to 510 kb of generated docs. I just tried and gzip takes that down to 70 kb when using default settings, 100 kb when using `--fast` and 69 kb when using `--best`. So yes, it looks to me like compressing the docs would certainly provide a good amount of breathing room 🙂

**Comment by ianmackenzie** [comment]
If necessary in my particular case I could split `elm-geometry` reasonably cleanly into `elm-2d-geometry` and `elm-3d-geometry`. So there is a workaround, but it would be moderately disruptive for dependent apps/packages, and I think having two separate packages would be a bit more annoying for everyone.

**Comment by evancz** [comment]
I believe the current version does that here https://github.com/elm/package.elm-lang.org/blob/master/src/backend/Package/Register.hs#L238

Please message me if you are still having trouble with this!
