### ISSUE TITLE
String module not present in module docs

### ISSUE THREAD

**Issue by i-hate-nicknames** [elm/package.elm-lang.org#323]
Steps to reproduce:
1. Open https://package.elm-lang.org/packages/elm/core/latest/
2. Type String in search form on the right.

It is hard to find String functions when string docs are not indexed by search engines, i.e. to find out how to convert integer to a string I had to go to the source code and read it to discover `fromInt` function.

**Comment by rlefevre** [comment]
Could you give some details?

For me, the `String` module is the first link when searching "elm string" on google:
![string_google](https://user-images.githubusercontent.com/5399281/72916458-5a479d00-3d42-11ea-9392-05b9983d6479.png)

and both the [`String` module](https://package.elm-lang.org/packages/elm/core/latest/String) and the [`String` type](https://package.elm-lang.org/packages/elm/core/latest/String#String) are linked on the right when I search "string" or "String" in the search box:
![search_string](https://user-images.githubusercontent.com/5399281/72916468-5ca9f700-3d42-11ea-9133-37048483ac08.png)

**Comment by i-hate-nicknames** [comment]
Indeed I am using DDG, so this one is covered.

After playing around for some ten minutes I was able to "reproduce the issue" but still couldn't understand how.

Finally it came: I have a bookmarked link for `elm-lang/core` page, I believe the language itself(?), while `elm/core` is a different package that actually has String module. I would go to that page and perform search there, assuming it's the right `core`.

What's interesting, you can go to https://package.elm-lang.org/packages/elm-lang/core/latest directly, but can't find `elm-lang/core` via search on https://package.elm-lang.org.

Well, sorry about all the fuss. Fancy search is a great tool that I definitely should've known about.

>PS: I wonder how you found the module source code without finding its documentation.

I just went to the source code manually to see if I can find anything about strings.

**Comment by rlefevre** [comment]
I see, no worries. `elm-lang/core` is the old version of `elm/core` for versions < 0.19, that's why it's not listed in the search results.
