### ISSUE TITLE
Site does not show contents on Firefox

### ISSUE THREAD

**Issue by Weyzu** [elm/package.elm-lang.org#335]
The page seems to not display any contents (aside from the navbar and side menu). Clicking on package details results in no content as well. Example:

![Adnotacja 2020-04-25 214903](https://user-images.githubusercontent.com/8172284/80289455-cde0b800-873e-11ea-9ca1-290104dd3bd4.png)

Web console spits out a couple of 

```
TypeError: e is undefined
```

wit thousands of repeats. I am wondering if anyone experiences the same problems.

Firefox version: 75.0

**Comment by rlefevre** [comment]
@Weyzu  I use Firefox 75.0 too and don't have issues.
Maybe you are using some web browser extension that conflicts with the virtual DOM, try disabling them and test again.

**Comment by Weyzu** [comment]
Indeed, it was one of the extensions. Thanks for the hint. :)
