### ISSUE TITLE
Cannot publish a 0.18 package 

### ISSUE THREAD

**Issue by jmbockhorst** [elm/package.elm-lang.org#336]
When trying to publish an Elm 0.18 package using: `elm package publish`, I get this error: 

```
Verifying EngageSoftware/intl-phone-input 1.0.0 ...
Error: The following HTTP request failed.
<http://package.elm-lang.org/versions?elm-package-version=0.18&name=EngageSoftware%2Fintl-phone-input>

A web handler threw an exception. Details:
corrupt JSON in legacy/all-packages.18.json
CallStack (from HasCallStack):
  error, called at src/backend/Legacy.hs:97:13 in main:Legacy
```

Here is the `elm-package.json`: https://github.com/EngageSoftware/intl-phone-input/blob/1.0.0/elm-package.json

**Comment by hpate-omicron** [comment]
I think this package may be the reason for the error, it is the only one that ends in a dash

```
    {
        "name": "joneshf/elm-",
        "summary": "Converts -- and --- to – and — respectively",
        "versions": [
            "1.0.0"
        ]
    },
```

**Comment by rlefevre** [comment]
A similar issue can be reproduced by clicking the following link:
http://package.elm-lang.org/versions?elm-package-version=0.18&name=elm-lang/core

**Comment by jmbockhorst** [comment]
Closing, as publishing 0.18 packages is not intended anymore.
