### ISSUE TITLE
Unpublish special-elektronik/elm-autocomplete due to organisation name change

### ISSUE THREAD

**Issue by carlfredrikhero** [elm/package.elm-lang.org#339]
The repo has moved to [specialelektronik/elm-autocomplete](https://github.com/Specialelektronik/elm-autocomplete) (notice the missing dash)

**Comment by pravdomil** [comment]
Add line to https://github.com/elm/package.elm-lang.org/blob/master/migration/Migrate.hs#L85.

**Comment by carlfredrikhero** [comment]
Great! Thanks @pravdomil
