### ISSUE TITLE
[urgent] add dark mode

### ISSUE THREAD

**Issue by dullbananas** [elm/package.elm-lang.org#345]

**Comment by bobwhitelock** [comment]
Why is this urgent?

**Comment by rlefevre** [comment]
Note that you can use https://dark.elm.dmy.fr until an official version is available.
It has [several other improvements too](https://discourse.elm-lang.org/t/unofficial-mobile-friendly-package-website-exploration/5180).

**Comment by evancz** [comment]
For now, I think it is best to go through @rlefevre's version for this feature.
